#!python3

from classy_blocks import Mesh, Face, Extrude
from pathlib import Path

l, r = 0.0, 1.0
t, b = 0.1, 0.0

p0 = [l, 0.0, t]
p1 = [r, 0.0, t]
p2 = [r, 0.0, b]
p3 = [l, 0.0, b]

# create base face and extrude to a hex
face = Face([p0, p1, p2, p3])
block = Extrude(face, amount=[0, 0.1, 0])

# set patches
block.set_patch("left", "inlet")
block.set_patch("right", "outlet")
block.set_patch("front", "frontAndBack")
block.set_patch("back", "frontAndBack")
block.set_patch("top", "upperWall")
block.set_patch("bottom", "lowerWall")  

mesh = Mesh()
mesh.add(block)

# update patches
mesh.modify_patch("frontAndBack", "empty")
mesh.modify_patch("upperWall", "wall")
mesh.modify_patch("lowerWall", "wall")

# x: flow direction
block.chop(0, count=100)
# z: back-front
block.chop(1, count=10)
# y: top-bottom: wall
block.chop(2, length_ratio=0.1, count=4)
block.chop(2, length_ratio=0.8, count=4)
block.chop(2, length_ratio=0.1, count=4)

dir=Path(__file__).parent
mesh.write(dir / "system"/ "blockMeshDict")
